import * as path from 'path';
import { mkdir, stat, writeFile } from 'mz/fs';
import { GeneratedCode, Role } from './types';
import { spawn } from './utils';

const tsconfig = {
  version: '2.4.2',
  compilerOptions: {
    lib: ['es2017', 'esnext'],
    target: 'es2017',
    module: 'commonjs',
    moduleResolution: 'node',
    emitDecoratorMetadata: true,
    experimentalDecorators: true,
    sourceMap: true,
    declaration: true,
    strict: true,
    outDir: '.',
  },
  include: [
    'src/*.ts',
  ],
  exclude: [
    'node_modules',
  ],
};

export class TSOutput {
  protected npm: (...args: string[]) => Promise<number>;
  protected tsc: (...args: string[]) => Promise<number>;

  protected constructor(protected readonly genPath: string) {
    this.npm = (...args: string[]) => spawn('npm', args, { cwd: genPath, stdio: 'inherit' });
    this.tsc = (...args: string[]) => spawn('tsc', args, { cwd: this.genPath, stdio: 'inherit' });
  }

  public static async create(genPath) {
    const st = await stat(genPath);
    if (!st.isDirectory()) {
      throw new Error(`output dir: ${genPath} is not a directory`);
    }
    return new this(genPath);
  }

  public async write(
    name: string,
    version: string,
    { code, pkg: basePackage }: GeneratedCode,
    role: Role
  ) {
    try {
      await mkdir(path.join(this.genPath, 'src'));
    } catch (err) {
      if (err.code !== 'EEXIST') {
        throw err;
      }
    }
    await Promise.all(Object.entries(code).map(
      ([n, c]) => writeFile(path.join(this.genPath, 'src', n), c)
    ));
    await writeFile(path.join(this.genPath, 'tsconfig.json'), JSON.stringify(tsconfig));
    const main = role === Role.ALL ? 'interfaces' : role;
    const pkgName = role === Role.ALL ? name : `${name}-${role}`;

    const pkg = {
      ...basePackage,
      main: `${main}.js`,
      description: 'Generated by launch',
      repository: 'undefined',
      types: `${main}.d.ts`,
      name: pkgName,
      version,
    };
    await writeFile(path.join(this.genPath, 'package.json'), JSON.stringify(pkg));
  }

  public async compile(): Promise<void> {
    await this.npm('i');
    await this.tsc();
  }

  public async publish(tag?: string): Promise<void> {
    if (tag) {
      await this.npm('publish', '--tag', tag);
    } else {
      await this.npm('publish');
    }
  }
}
